sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t troig/learn-docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true troig/learn-docker-kubernetes npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "learn-docker-kubernetes"
  env: "LearnDockerKubernetes-env"
  bucket_name: "elasticbeanstalk-eu-west-1-062793652651"
  bucket_path: "learn-docker-kubernetes"
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

