sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t troig/learn-docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true troig/learn-docker-kubernetes npm run test
